### ISSUE TITLE
Feature Request: `only` trait - opposite if `disabled`

### ISSUE THREAD

**Issue by Sajjon** [apple/swift-testing#70]
### Description

Using swift-testing with a mid October toolchain, Xcode 15.0.1 and Sonoma, I do not see any test “diamonds” in Xcode.

Thus I cannot start a specific test, and run only that test. Annoying! 

The `disabled` trait exist, and I think we should add the reverse - an `only` trait.

[Jest has this](https://jestjs.io/docs/setup-teardown#general-advice) 

What should happen if one accidentally declares more than one `only`? Compilation error would be good! 

### Expected behavior

To be able to run a specific test.

### Actual behavior

Have to run all test now.

### swift-testing version/commit hash

f8e8961b48d53d3272dacd7431257ed87260b3a1

### Swift & OS version (output of `swift --version && uname -a`)
```
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-macosx14.0
Darwin Alexanders-MacBook-Pro.local 23.1.0 Darwin Kernel Version 23.1.0: Tue Oct  3 22:40:26 PDT 2023; root:xnu-10002.41.8~15/RELEASE_ARM64_T6020 arm64
```

**Comment by Sajjon** [comment]
Regarding the underlying issue of missing "diamond" button in Xcode 15, seems more users have experienced this: https://forums.swift.org/t/missing-test-diamonds-in-xcode/62543/11

But the `only` feature is still good! Since it allows running single test from CLI or other IDEs than Xcode.

**Comment by grynspan** [comment]
Traits affect specific tests and, in the case of test suites, any tests they contain. It is intentional that they do not have the power to affect _other_ tests, because that would make computing test plans intractably complex.

During macro expansion, the macro plugin cannot "see" symbols beyond the one being expanded upon, so it is not possible to detect that two tests both have a `.only` trait. Additionally, type information is not available during macro expansion, so it is trivally easy to accidentally escape the diagnostic logic (e.g. by using a trait declared as `let myOnly = OnlyTrait.only` or similar, which the macro plugin wouldn't know represented the same trait type.)

Technical constraints aside, the general utility of a `.only` trait seems limited. If you are writing many tests and only want to run a single one, that's something that (I think!) would be typically modelled through tooling, not in the source of the test suite itself. If and when we're able to augment `swift test --filter` to understand swift-testing, I think we'd suggest you use it to run individual tests. Does that sound reasonable?
